name: Wildernether

author: SchnTgaiSpock

description: Adds plants, mob drops, food, and more to the nether

main: me.schntgaispock.wildernether.Wildernether

website: https://github.com/SchnTgaiSpock/Wildernether

version: ${project.version}

api-version: 1.14

depend:
  - Slimefun
  - GuizhanLibPlugin

softdepend:
  - SlimeHUD
  - Gastronomicon

loadbefore:
  - SlimeCustomizer
  - RykenSlimeCustomizer


